In [74]:
import pandas as ps
import plotly
import plotly.plotly as py
import plotly.graph_objs as go
plotly.tools.set_credentials_file(username='hali96', api_key='y8861qxd0n')

In [75]:
fall2015 = ps.read_excel(open('falldata.xls', 'rb'), sheetname='By Structure')

hopkins = []
pang = []
torpinS = []
torpinN = [] 
gilman = []
eastC1E = []
eastC1W = []
arbor = []
bachman = []
arbor140 = [] 

for i in range (3, 13):
    hopkins.append(fall2015.ix[7][i])
    pang.append(fall2015.ix[18][i])
    torpinS.append(fall2015.ix[29][i])
    torpinN.append(fall2015.ix[40][i])
    gilman.append(fall2015.ix[52][i])

print(hopkins)
print(pang)
print(torpinS)
print(torpinN)
print(gilman)

almostdone = [hopkins, pang, torpinS, torpinN, gilman]

almostdone

[16, 0, 0, 1, 0, 1, 4, 1, 4, 16]
[29, 5, 0, 0, 0, 0, 1, 1, 7, 11]
[4, 3, 2, 1, 1, 2, 2, 2, 3, 3]
[5, 4, 0, 0, 1, 1, 1, 0, 2, 3]
[126, 62, 3, 0, 0, 0, 0, 22, 22, 44]

[[16, 0, 0, 1, 0, 1, 4, 1, 4, 16],
 [29, 5, 0, 0, 0, 0, 1, 1, 7, 11],
 [4, 3, 2, 1, 1, 2, 2, 2, 3, 3],
 [5, 4, 0, 0, 1, 1, 1, 0, 2, 3],
 [126, 62, 3, 0, 0, 0, 0, 22, 22, 44]]

In [76]:
fall2015

,"University of California, San Diego Survey of Parking Space Occupancy Levels, Fall 2015",Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12,Unnamed: 13,Unnamed: 14,Unnamed: 15
0,By Structure,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Structure,Parking,Parking,Average Empty Parking Spaces,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,At Peak,NaN,NaN
3,NaN,Space,Spaces,8:00,9:00,10:00,11:00,12:00,1:00,2:00,3:00,4:00,5:00,Empty,Occupied,%
4,NaN,NaN,NaN,am,am,am,am,pm,pm,pm,pm,pm,pm,Spaces,Spaces,Occupied
5,Hopkins,A,80,68,57,37,25,16,15,9,13,20,26,9,71,0.8875
6,NaN,B,495,421,291,119,9,0,2,4,13,43,129,0,495,1
7,NaN,S,674,16,0,0,1,0,1,4,1,4,16,0,674,1
8,NaN,Visitor,92,80,69,42,21,5,11,19,20,30,38,5,87,0.945652
9,NaN,Reserved,1,1,0,0,0,0,0,0,0,0,0,0,1,1
10,NaN,Allocated,18,15,13,9,4,3,4,4,4,5,6,3,15,0.833333
11,NaN,Accessible,25,22,19,18,19,13,16,18,19,17,19,13,12,0.48
12,NaN,UC Vehicle,10,3,2,3,3,3,4,3,4,5,4,2,8,0.8
13,NaN,Service Yard,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,NaN,Loading,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,NaN,Total,1395,626,451,228,82,40,53,61,74,124,238,40,1355,0.971326
16,Pangea,A,80,60,55,45,24,13,10,10,14,21,32,10,70,0.875
17,NaN,B,185,114,89,29,0,1,1,3,9,24,55,0,185,1
18,NaN,S,550,29,5,0,0,0,0,1,1,7,11,0,550,1
19,NaN,Visitor,109,104,99,79,45,20,13,21,23,48,58,13,96,0.880734
20,NaN,Reserved,8,4,4,5,4,5,5,5,5,4,4,4,4,0.5
21,NaN,Allocated,6,2,3,2,2,1,2,1,2,3,2,1,5,0.833333
22,NaN,Accessible,15,11,10,10,8,8,9,7,7,9,9,7,8,0.533333
23,NaN,UC Vehicle,8,3,4,4,4,1,2,4,2,3,3,1,7,0.875
24,NaN,Service Yard,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,Loading,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,NaN,Total,961,327,269,174,87,49,42,52,63,119,174,42,919,0.956296
27,Torrey,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,Pines,B,392,208,121,65,55,64,75,66,64,134,248,55,337,0.859694
29,Center,S,4,4,3,2,1,1,2,2,2,3,3,1,3,0.75
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,NaN,Visitor,273,175,136,88,65,67,77,68,69,94,121,65,208,0.761905
86,NaN,Reserved,19,17,17,15,15,14,14,14,17,13,15,13,6,0.315789
87,NaN,Allocated,8,6,4,5,5,3,5,4,5,5,6,3,5,0.625
88,NaN,Accessible,15,2,2,1,2,2,4,3,3,5,6,1,14,0.933333
89,NaN,UC Vehicle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
90,NaN,Service Yard,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
91,NaN,Loading,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
92,NaN,Total,553,381,302,213,168,160,171,159,171,200,258,159,394,0.712477
93,Bachman,A,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
94,NaN,B,1000,270,91,31,14,20,24,27,71,214,409,14,986,0.986
95,NaN,S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
96,NaN,Visitor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
97,NaN,Reserved,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
98,NaN,Allocated,26,21,20,19,13,12,10,12,7,7,6,6,20,0.769231
99,NaN,Accessible,6,4,4,3,2,3,3,3,2,4,6,2,4,0.666667
100,NaN,UC Vehicle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
101,NaN,Service Yard,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
102,NaN,Loading,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
103,NaN,Total,1032,295,115,53,29,35,37,42,80,225,421,29,1003,0.971899
104,140 Arbor,A,9,9,8,7,7,6,7,6,5,5,6,5,4,0.444444
105,NaN,B,21,12,8,4,4,4,4,5,6,10,11,4,17,0.809524
106,NaN,S,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
107,NaN,Visitor,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108,NaN,Reserved,4,4,4,3,3,3,3,3,3,3,3,3,1,0.25
109,NaN,Allocated,42,42,41,37,31,27,26,23,26,28,36,23,19,0.452381
110,NaN,Accessible,4,4,3,3,3,3,3,3,3,3,4,3,1,0.25
111,NaN,UC Vehicle,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,NaN,Service Yard,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
113,NaN,Loading,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,NaN,Total,80,71,64,54,48,43,43,40,43,49,60,40,40,0.5

In [77]:
index = ["Hopkins", "Pangea", "Torrey Pines Center South", "Torrey Pines Center North", "Gilman"]
columns = ["8am", "9am", "10am", "11am", "12pm", "1pm", "2pm", "3pm", "4pm", "5pm"]

In [78]:
Sspots = ps.DataFrame(almostdone, index=index, columns=columns)
Sspots

                           8am  9am  10am  11am  12pm  1pm  2pm  3pm  4pm  5pm
Hopkins                     16    0     0     1     0    1    4    1    4   16
Pangea                      29    5     0     0     0    0    1    1    7   11
Torrey Pines Center South    4    3     2     1     1    2    2    2    3    3
Torrey Pines Center North    5    4     0     0     1    1    1    0    2    3
Gilman                     126   62     3     0     0    0    0   22   22   44

In [79]:
data = [go.Heatmap(z = almostdone, x = columns, y = index, zmax = 2000, 
                  colorscale = 'PRGn')]
py.iplot(data, filename='WeAreDone')

High five! You successfuly sent some data to your account on plotly. View your plot in your browser at https://plot.ly/~hali96/0 or inside your plot.ly account where it is named 'WeAreDone'